version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_data:/usr/share/nginx/html/uploads
    depends_on:
      - backend

volumes:
  uploads_data: